lib/worker.coffee
when `Safe Mode` is not `secure` `include::doc.adoc[]` does not work, it prints `Unresolved directive in <stdin> - include::doc.adoc[]`
this patch fixes it.
=> fix include::

lib/asciidoc-preview.coffee
We are seeing a duplicate entry in the config settings for the toc.
* Show Table of Content
* Show Toc
This patch removes the first entry, which is unused.
=> fix name of default toc config setting

lib/asciidoc-preview-view.coffee, lib/asciidoc-preview.coffee, lib/renderer.coffee, lib/worker.coffee, menus/asciidoc-preview.cson
Related to issue #99 this PR makes it easier to set the currently available `top` options: none (blank), preamble and macro.
This PR:
* Changes the checkbox configuration in the settings panel by a multi-select option.
* Replaces the context menu with a sub-menu with the different options.
Any comments will be greatly appreciated, I’m not into front-end/web techs and almost everything here is new to me.
=> improved toc configuration using a select option instead of a toogle

lib/asciidoc-preview-view.coffee, lib/asciidoc-preview.coffee, lib/renderer.coffee, lib/worker.coffee, menus/asciidoc-preview.cson
Files with frontmatter mess up the preview. I guess in most cases one can simply ignore it.
=> add skip-front-matter to default attributes

lib/asciidoc-preview-view.coffee
=> Resolves #125, escape ': . [ ] , ( )' characters in links

lib/renderer.coffee
No direct dependence with Highlights because it requires a compilation.
See #63 and #150 and atom/highlights#36.
=> fix: Highlights dependency

lib/asciidoc-preview-view.coffee, lib/extension-helper.coffee, lib/main.coffee, lib/renderer.coffee, lib/worker.coffee, menus/asciidoc-preview.cson
- set compat-mode to false by default.
- add `force experimental`
- `skipFrontMatter` become `frontMatter` : positive expression always better!
- add descriptions for options
- ordering options
- use enum for the safe mode definition
- change 'Show Table of Content' to 'Force show Table of Content', add explanations
=> feat: more user friendly settings

lib/asciidoc-preview-view.coffee, lib/main.coffee, lib/renderer.coffee, menus/asciidoc-preview.cson, package.json
Rethink the section numbering option:
- soft on: Turn it on unless the document turns it off (`-a sectnums=@`) **Default**
- Always on (`-a sectnums`)
- Always off (`-a sectnums!`)
- Let the document decide
Fix  #58
=> feature: section numbering

lib/main.coffee, lib/renderer.coffee, menus/asciidoc-preview.cson, package.json
Rename section numbering options:
- 'soft on' become 'Enabled by default'
- 'Always on' become 'Always enabled'
- 'Always off' become 'Always disabled'
- 'Let the document decide' become 'Not specified'
=> refactor: section numbering menu

lib/asciidoc-preview-view.coffee, package.json
Restore preview after close or reload Atom.
- preview a document
- close Atom or reloafd (<kbd>crtl+alt+R</kbd>)
- the preview is always opened
Know bug: the pane icon after a restore is breaking. (workaround: close and re-open the preview)
=> refactor: add deserializer configuration

lib/renderer.coffee
Your description.
```adoc
[subs=+quotes]
----
[ ... Output Abbreviated ... ]
2: em1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
link/ether d4:be:d9:b3:8e:0f brd ff:ff:ff:ff:ff:ff
inet 10.16.154.0/21 brd 10.16.159.255 scope global dynamic em1
valid_lft 73367sec preferred_lft 73367sec
inet6 fe80::d6be:d9ff:feb3:8e0f/64 scope link
valid_lft forever preferred_lft forever
[ ... Output Abbreviated ... ]
----
[options="nowrap", subs="+quotes"]
----
http_proxy=http://__proxy-ip-or-hostname__:__port-number__
----
```
Before:
After:
Fix  #102
=> fix: substitutions quotes

lib/main.coffee, menus/asciidoc-preview.cson, package.json, spec/fixtures/test.asciidoc
**Experimental feature.**
Export as PDF.
Use [asciidoctor-pdf](https://github.com/asciidoctor/asciidoctor-pdf).
Tested with:
Related to  #167
=> feature: export as PDF (experimental)

lib/renderer.coffee, lib/worker.coffee
On Windows, AsciiDoctor.js try to write when a document have syntax error but this crash the preview.
Now an error page appear.
See #172 ansd #159.
=> feat: add error page for rendering

lib/renderer.coffee, lib/std-stream-hook.coffee, lib/worker.coffee
On Windows, AsciiDoctor.js try to write on `process.stdout` and `process.stderr` when a document have syntax error but this crash the preview.
Now the errors are properly displayed in the console and the document is rendered.
I removed the specific message in the error page.
Fix #172 and #159.
Related to https://github.com/electron/electron/issues/2033
=> Windows stdout hook

lib/attributes-builder.coffee, lib/renderer.coffee, lib/worker.coffee, spec/attributes-builder-spec.coffee
Move the construct of `base_dir` from `worker.coffee` to `attributes-builder.coffee`
=> refactor: move base directory construct

lib/asciidoc-preview-view.coffee, package.json
Allow to automatically open generated HTML in the default browser.
=> feat: open generated HTML file in browser

lib/asciidoc-preview-view.coffee, lib/attributes-builder.coffee, package.json, spec/attributes-builder-spec.coffee
Advanced base directory management.
- `base_dir`
Related to #182
```adoc
include::/home/ldez/foobar.doc[]
```
=> feat: base directory management

lib/renderer.coffee
Refresh image. (must close and reopen preview or only edit document)
Fix #95
=> feat: invalidate image cache

lib/configuration-builder.coffee, lib/renderer.coffee
Fix raw text code block highlighting. 
```adoc
= Test
[subs="+quotes"]
----
__JWS_HOME__\sbin\tomcat__<VERSION>__.exe //US//Tomcat__<VERSION>__ ++JvmOptions="-Dcom.sun.management.jmxremote.port=8100;-Dcom.sun.management.jmxremote.access.file="C:\jmx\jmxremote.access";-Dcom.sun.management.jmxremote.password.file="C:\jmx\jmxremote.password";-Dcom.sun.management.jmxremote.ssl=false;-Dcom.sun.management.jmxremote.authenticate=true"
----
```
Fix #193
Related to #102
=> fix: text code block

lib/pdf-converter.coffee, package.json
Related to Atom 1.9 update.
Fixed on Windows, Linux and MacOS
Fix #195
=> fix(pdf): remove bash interactive option

lib/pdf-converter.coffee
The "AsciiDoc: Export as PDF" option fails for files with whitespaces in them and complains for a missing file with an incomplete filename.
```adoc
= Title
== Test
This is a test.
```
Fix #212
=> feat(pdf): support filenames with whitespaces.

lib/asciidoc-preview-view.coffee
Fix wrong file path when save as HTML and open in the default browser.
Fix #224
=> fix: wrong file path when save as HTML.

lib/renderer.coffee
Fix Highlights module path on Fedora.
Fixes #223, #226
=> fix: Highlights on Fedora.

styles/asciidoc-preview.less
Set the overflow on the y axis to `scroll`, but set the overflow on the x axis to `auto`.
```adoc
[source,ruby]
----
require 'asciidoctor/extensions'
Asciidoctor::Extensions.register do
treeprocessor do
process do |doc|
(doc.find_by context: :dlist).each do |dlist|
dlist.style = 'horizontal'
end
nil
end
end
end
----
oh
here
it
goes
again
```
Fix #233
=> Don't force scrolling on the x axis

lib/highlights.coffee, lib/renderer.coffee, package.json, styles/asciidoc-preview.less
Atom CSS parsing changes broke the source highlighting in the preview pane.
Use the same approach than [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus/blob/master/lib/renderer.coffee).
See https://github.com/atom-haskell/atom-highlights.
```adoc
[source, js]
----
var http = require('http');
http.createServer(function (req, res) {
res.end('Hello World\n');
}).listen(1337, '127.0.0.1');
----
```
Fix #229
=> refactor: change Highlights provider.

lib/asciidoc-preview-view.coffee, package.json
Save as HTML with Atom 1.24.
Due to https://github.com/atom/atom/pull/16245.
Fixes #258
cc @kachkaev
=> Save as HTML with Atom 1.24.

lib/highlights-helper.coffee, lib/renderer.coffee
Allow highlight for PHP even without starting <?php.
```adoc
[source,php]
----
echo "highlight me please";
----
```
=> Allow highlight for PHP even without <?php

lib/asciidoc-preview-view.coffee
- use document.getElementById('ID') instead of $('#ID')
Fixes #276
=> Use safe ID lookup

README.md
Following the discussion [here](https://github.com/asciidoctor/atom-asciidoc-preview/issues/282), I am proposing this change in the README.
=> Update the readme with the :toc: left thingy

lib/asciidoc-preview-view.coffee
The package has been renamed to `@asciidoctor/core` in Asciidoctor.js 2.0.
So the path to the default stylesheet is now:
`node_modules/@asciidoctor/core/dist/css/asciidoctor.css`.
resolves #296
=> Fix the path to the default stylesheet

README.md
[GitHub is sunsetting Atom on December 15, 2022](https://github.blog/2022-06-08-sunsetting-atom/) 
Thanks to [all contributors](https://github.com/asciidoctor/atom-asciidoc-preview/graphs/contributors) ❤️, it's time to move on 🥲
=> Sunsetting Atom
