- keymaps/asciidoc-preview.cson
- stylesheets/asciidoc-preview.less
> Deprecated fixes

- lib/asciidoc-preview.coffee
Add `data-uri!` to default attributes
> Disable data-uri by default - fixes issue #97

- styles/asciidoc-preview.less
> Resolves #105, use #333 color for text

- .coffeelintignore
- .editorconfig
- .travis.yml
- README.md
- appveyor.yml
- coffeelint.json
- lib/asciidoc-preview-view.coffee
- lib/asciidoc-preview.coffee
- lib/attributes-provider.coffee
- lib/renderer.coffee
- lib/worker.coffee
- menus/asciidoc-preview.cson
- spec/acsiidoc-preview-spec.coffee
- coffeelint config
- code linting
- first spec
> chore: Travis CI & AppVeyor

- lib/worker.coffee
- package.json
- styles/asciidoc-preview.less
- Bump version to 0.7.0
- Remove unused dependencies
- Fix dependency version
Remove `temp`, `opal-npm-wrapper` (transitive) and `wrench` dependency.
Resolves #108
> Upgrade to Asciidoctor 1.5.4 (version 1.5.5-1)

- menus/asciidoc-preview.cson
> fix: preview link

- .travis.yml
- appveyor.yml
> Prepare tests

- lib/asciidoc-preview-view.coffee
- lib/asciidoc-preview.coffee
- lib/main.coffee
- lib/renderer.coffee
- lib/worker.coffee
- package.json
Remove Markdown Preview dependency.
Fix #31
> feat: remove Markdown Preview dependency

- package.json
> fix: remove Highlights dependency

- keymaps/asciidoc-preview.cson
> feat: Settings to disable package keybinding

- README.md
- lib/asciidoc-preview-view.coffee
- lib/extension-helper.coffee
- lib/main.coffee
- lib/renderer.coffee
- menus/asciidoc-preview.cson
- package.json
- choose display pane
- open from tree view
- language highlight insensitive case
- code review
- enhance readme
> Choose display pane & open from tree view

- styles/asciidoc-preview.less
> fix: loading gif size

- lib/attributes-builder.coffee
- lib/main.coffee
- lib/pdf-converter.coffee
- lib/worker.coffee
- spec/attributes-builder-spec.coffee
- isolate PDF converter
- add tests on AttributesBuilder
I have write those tests when I created the AttributesBuilder but I think I have crashing them...
> Refactor: pdf converter

- lib/pdf-converter.coffee
- package.json
Allow to automatically open generated PDF in the default PDF viewer.
> feat: open PDF after generating

- lib/asciidoc-preview-view.coffee
- lib/main.coffee
Fix 'render on save' 
Fix #180
> Fix: render on save

- lib/asciidoc-preview-view.coffee
- lib/main.coffee
- remove dead code
- coffee style
> refactor: remove dead code

- lib/renderer.coffee
> refactor: safe rendering

- lib/configuration-builder.coffee
- lib/renderer.coffee
- lib/worker.coffee
- spec/configuration-builder-spec.coffee
Split options and attributes.
Related to #178 and  #169
> refactor: split options and attributes

- lib/worker.coffee
- package.json
Upgrade to Asciidoctor.js 1.5.5-4 from 1.5.5-1.
> Upgrade to Asciidoctor.js 1.5.5-4

- package.json
- templates/default.html
Update font-awesome and other libraries.
> feat: update libraries versions.

- .travis.yml
- appveyor.yml
Related to https://github.com/atom/ci
> chore: update CI configuration.

- lib/pdf-converter.coffee
- package.json
Add support for asciidoctor-pdf additional arguments.
Useful for themes.
Fixes #208
> feat: Add support for asciidoctor-pdf additional arguments.

- README.md
Clarify readme and options spotlight.
> doc: enhance readme.

- lib/asciidoc-preview-view.coffee
- lib/pdf-converter.coffee
- menus/asciidoc-preview.cson
Add pdf export entry to preview menu
Related to #237
> feat: add pdf export entry to preview menu.

- .travis.yml
Fix build on Travis : Atom Beta & Linux
Related to https://github.com/atom/ci/issues/69
> fix: Atom Beta on Linux with Travis.

- lib/highlights.coffee
Encode HTML entities.
```adoc
[source,xml]
----
<profiles>
<function> </function>
<first_name></first_name>
<last_name></last_name>
<e-mail></e-mail>
<company_name></company_name>
</profiles>
----
[source, html]
----
value.replace('&', '&amp;').replace('<', '&lt;')
----
[source, js]
----
value.replace('&', '&amp;').replace('<', '&lt;')
----
```
Fixes #241
> feat(highlights): encode HTML entities.

- .github/PULL_REQUEST_TEMPLATE.md
- lib/asciidoc-preview-view.coffee
> Save as HTML: fix title

- lib/configuration-builder.coffee
- lib/worker.coffee
- package.json
- spec/configuration-builder-spec.coffee
- spec/worker-blocks-positions-spec.coffee
Upgrade to the latest release of Asciidoctor.js: https://github.com/asciidoctor/asciidoctor.js/releases/tag/v1.5.6-rc.1
Should resolve #205
> Upgrade to Asciidoctor.js 1.5.6

- lib/renderer.coffee
- spec/highlights-helper-spec.coffee
> Sanitize scope name.

- README.md
Mention the TOC under options. Briefly explain the options.
> mention TOC options in README [skip ci]

- package.json
- spec/worker-blocks-positions-spec.coffee
Upgrade to Asciidoctor.js 1.5.9
resolves #289 
resolves #287
> Upgrade to Asciidoctor.js 1.5.9
